version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22  # Use the Node.js version your app requires
    commands:
      - echo Installing dependencies...
      - npm install
  
  build:
    commands:
      - echo Building the React app...
      - npm run build

  post_build:
    commands:
      - echo Syncing files to S3...
      # - aws s3 sync build/ s3://your-s3-bucket-name --delete
      - echo Invalidating CloudFront cache...
      # - aws cloudfront create-invalidation --distribution-id YOUR_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
